### PR TITLE
Require DJANGO_KEY to be set statically

### PR DESCRIPTION
**Pull request by lgruen**
Otherwise sessions get invalidated each time the service is restarted.

### CODE REVIEW

**Review by illusional — APPROVED** [review]
Has this been set on the server, and is it documented that you'd have to set this somewhere, like I don't imagine we're using any infrastructure as code to set it right?

**Comment by illusional** [comment]
Tests are still failing, but now earlier on your change:

```
File "/home/runner/work/seqr/seqr/settings.py", line 186, in <module>
33
    assert SECRET_KEY and len(SECRET_KEY) == 50
34
AssertionError
35
Coverage.py warning: No data was collected. (no-data-collected)
```

**Comment by lgruen** [comment]
> Tests are still failing, but now earlier on your change:

Thanks! I've reverted to generating the key in the non-{prod,dev} deployments, like unit tests.

The failures (as discussed in https://github.com/populationgenomics/seqr/pull/6) seem unrelated to this particular change, so I'll merge them for now.

**Comment by lgruen** [comment]
> Has this been set on the server, and is it documented that you'd have to set this somewhere, like I don't imagine we're using any infrastructure as code to set it right?

This has been set in the deployments that I'm currently using, but those haven't been committed yet. There's still an odd issue about HTTP load balancers in front of Cloud Run deployments in the australia-southeast1 region that I'm waiting for support to respond to.

**Comment by lgruen** [comment]
The tests are passing now. I'll merge this and open up a new PR with the Cloud Run configurations.

**Pull request merged**
