### PR TITLE
Gh actions

### PR DESCRIPTION
**Pull request by illusional**
I modified all three of the GH actions to run on pushes to `main`, and changed the cron time to be `9am AEST / 10am AEDT`. 

A few notes:

- I don't know if we have to keep the `local-install-tests`
- The trivy tests run this custom action: https://github.com/broadinstitute/dsp-appsec-trivy-action, but the "blessed images" link they post is hidden to me: https://github.com/broadinstitute/dsp-appsec-blessed-images

I don't think this PR should be merged, just here to create conversation

### CODE REVIEW

**Comment by lgruen** [comment]
Thanks! I agree that we probably don't care about `local-install-tests`, although I'm trying to keep overall changes as minimal as possible to keep merging upstream changes easy. Do you understand why the unit tests are failing currently?

Some sort of automated security review would be nice to have. Is there a generic trivy equivalent that we could use.

In terms of deployment, I was thinking of the following, but eager to hear your feedback:
- Build a seqr Docker image on merge with main, deploy that to seqr-dev.
- Add a manually triggered action that deploys to seqr(-prod).

**Comment by illusional** [comment]
Maybe we should have an intermediate `dev` branch (like seqr originally does), merges to seqr@dev deploy to seqr-dev, and merges to main reflect prod. I'll have a look for more generic trivy actions.

**Comment by lgruen** [comment]
> Maybe we should have an intermediate `dev` branch (like seqr originally does), merges to seqr@dev deploy to seqr-dev, and merges to main reflect prod.

I like that idea a lot. Let's do that!

> The unit tests are failing because it can't reach certain resources: https://github.com/populationgenomics/seqr/runs/2188422413?check_suite_focus=true

It's odd that this still happens after having removed our customizations. I also can't find any references to GitHub secrets in the workflows, so why is it behaving differently...? 🤔

**Comment by lgruen** [comment]
> It's odd that this still happens after having removed our customizations. I also can't find any references to GitHub secrets in the workflows, so why is it behaving differently...? 🤔

Oh, it's probably because of https://github.com/populationgenomics/seqr/commit/7b814b2eec7ab140b67d1e2b675cc7ac3268fe65. I'll send you a revert for that, too. I was doing that to get the UI working, but that might not be that important anyway.

**Review by lgruen — APPROVED** [review]

**Pull request merged**
